# Generated by Django 5.0.2 on 2024-02-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantries', '0002_alter_pantryitem_options_pantryitem_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pantry',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Pantry', 'verbose_name_plural': 'Pantries'},
        ),
        migrations.AddField(
            model_name='pantry',
            name='name',
            field=models.CharField(default='Pantry', max_length=120),
        ),
    ]
